import BiMap from 'mnemonist/bi-map';

export const alphabetBiMap = BiMap.from({
    A: 0, B: 1, C: 2, D: 3, E: 4, F: 5, G: 6, H: 7, I: 8, J: 9, K: 10,
    L: 11, M: 12, N: 13, O: 14, P: 15, Q: 16, R: 17, S: 18, T: 19, U: 20,
    V: 21, W: 22, X: 23, Y: 24, Z: 25
});

export const Rotors = {
    I: { 
        wiring: BiMap.from({
            A: 'E',
            B: 'K',
            C: 'M',
            D: 'F',
            E: 'L',
            F: 'G',
            G: 'D',
            H: 'Q',
            I: 'V',
            J: 'Z',
            K: 'N',
            L: 'T',
            M: 'O',
            N: 'W',
            O: 'Y',
            P: 'H',
            Q: 'X',
            R: 'U',
            S: 'S',
            T: 'P',
            U: 'A',
            V: 'I',
            W: 'B',
            X: 'R',
            Y: 'C',
            Z: 'J'
        }),
        turnOvers: ['Q']
    },
    II: {
        wiring: BiMap.from({
            A: 'A',
            B: 'J',
            C: 'D',
            D: 'K',
            E: 'S',
            F: 'I',
            G: 'R',
            H: 'U',
            I: 'X',
            J: 'B',
            K: 'L',
            L: 'H',
            M: 'W',
            N: 'T',
            O: 'M',
            P: 'C',
            Q: 'Q',
            R: 'G',
            S: 'Z',
            T: 'N',
            U: 'P',
            V: 'Y',
            W: 'F',
            X: 'V',
            Y: 'O',
            Z: 'E'
        }),
        turnOvers: ['E']
    },
    III: {
        wiring: BiMap.from({
            A: 'B',
            B: 'D',
            C: 'F',
            D: 'H',
            E: 'J',
            F: 'L',
            G: 'C',
            H: 'P',
            I: 'R',
            J: 'T',
            K: 'X',
            L: 'V',
            M: 'Z',
            N: 'N',
            O: 'Y',
            P: 'E',
            Q: 'I',
            R: 'W',
            S: 'G',
            T: 'A',
            U: 'K',
            V: 'M',
            W: 'U',
            X: 'S',
            Y: 'Q',
            Z: 'O'
        }),
        turnOvers: ['V']
    },
    IV: {
        wiring: BiMap.from({
            A: 'E',
            B: 'S',
            C: 'O',
            D: 'V',
            E: 'P',
            F: 'Z',
            G: 'J',
            H: 'A',
            I: 'Y',
            J: 'Q',
            K: 'U',
            L: 'I',
            M: 'R',
            N: 'H',
            O: 'X',
            P: 'L',
            Q: 'N',
            R: 'F',
            S: 'T',
            T: 'G',
            U: 'K',
            V: 'D',
            W: 'C',
            X: 'M',
            Y: 'W',
            Z: 'B'
        }),
        turnOvers: ['J']
    },
    V: {
        wiring: BiMap.from({
            A: 'V',
            B: 'Z',
            C: 'B',
            D: 'R',
            E: 'G',
            F: 'I',
            G: 'T',
            H: 'Y',
            I: 'U',
            J: 'P',
            K: 'S',
            L: 'D',
            M: 'N',
            N: 'H',
            O: 'L',
            P: 'X',
            Q: 'A',
            R: 'W',
            S: 'M',
            T: 'J',
            U: 'Q',
            V: 'O',
            W: 'F',
            X: 'E',
            Y: 'C',
            Z: 'K'
        }),
        turnOvers: ['Z']
    },
    VI: {
        wiring: BiMap.from({
            A: 'J',
            B: 'P',
            C: 'G',
            D: 'V',
            E: 'O',
            F: 'U',
            G: 'M',
            H: 'F',
            I: 'Y',
            J: 'Q',
            K: 'B',
            L: 'E',
            M: 'N',
            N: 'H',
            O: 'Z',
            P: 'R',
            Q: 'D',
            R: 'K',
            S: 'A',
            T: 'S',
            U: 'X',
            V: 'L',
            W: 'I',
            X: 'C',
            Y: 'T',
            Z: 'W'
        }),
        turnOvers: ['Z', 'M']
    },
    VII: {
        wiring: BiMap.from({
            A: 'N',
            B: 'Z',
            C: 'J',
            D: 'H',
            E: 'G',
            F: 'R',
            G: 'C',
            H: 'X',
            I: 'M',
            J: 'Y',
            K: 'S',
            L: 'W',
            M: 'B',
            N: 'O',
            O: 'U',
            P: 'F',
            Q: 'A',
            R: 'I',
            S: 'V',
            T: 'L',
            U: 'P',
            V: 'E',
            W: 'K',
            X: 'Q',
            Y: 'D',
            Z: 'T'
        }),
        turnOvers: ['Z', 'M']
    },
    VIII: {
        wiring: BiMap.from({
            A: 'F',
            B: 'K',
            C: 'Q',
            D: 'H',
            E: 'T',
            F: 'L',
            G: 'X',
            H: 'O',
            I: 'C',
            J: 'B',
            K: 'J',
            L: 'S',
            M: 'P',
            N: 'D',
            O: 'Z',
            P: 'R',
            Q: 'A',
            R: 'M',
            S: 'E',
            T: 'W',
            U: 'N',
            V: 'I',
            W: 'U',
            X: 'Y',
            Y: 'G',
            Z: 'V'
        }),
        turnOvers: ['Z', 'M']
    }
};

export const GreekWheels = {
    beta: BiMap.from({
        A: 'L',
        B: 'E',
        C: 'Y',
        D: 'J',
        E: 'V',
        F: 'C',
        G: 'N',
        H: 'I',
        I: 'X',
        J: 'W',
        K: 'P',
        L: 'B',
        M: 'Q',
        N: 'M',
        O: 'D',
        P: 'R',
        Q: 'T',
        R: 'A',
        S: 'K',
        T: 'Z',
        U: 'G',
        V: 'F',
        W: 'U',
        X: 'H',
        Y: 'O',
        Z: 'S'
    }),
    gamma: BiMap.from({
        A: 'F',
        B: 'S',
        C: 'O',
        D: 'K',
        E: 'A',
        F: 'N',
        G: 'U',
        H: 'E',
        I: 'R',
        J: 'H',
        K: 'M',
        L: 'B',
        M: 'T',
        N: 'I',
        O: 'Y',
        P: 'C',
        Q: 'W',
        R: 'L',
        S: 'Q',
        T: 'P',
        U: 'Z',
        V: 'X',
        W: 'V',
        X: 'G',
        Y: 'J',
        Z: 'D'
    })
};

export const Reflectors = {
    b: BiMap.from({
        A: 'E',
        B: 'N',
        C: 'K',
        D: 'Q',
        E: 'A',
        F: 'U',
        G: 'Y',
        H: 'W',
        I: 'J',
        J: 'I',
        K: 'C',
        L: 'O',
        M: 'P',
        N: 'B',
        O: 'L',
        P: 'M',
        Q: 'D',
        R: 'X',
        S: 'Z',
        T: 'V',
        U: 'F',
        V: 'T',
        W: 'H',
        X: 'R',
        Y: 'G',
        Z: 'S'
    }),
    c: BiMap.from({
        A: 'R',
        B: 'D',
        C: 'O',
        D: 'B',
        E: 'J',
        F: 'N',
        G: 'T',
        H: 'K',
        I: 'V',
        J: 'E',
        K: 'H',
        L: 'M',
        M: 'L',
        N: 'F',
        O: 'C',
        P: 'W',
        Q: 'Z',
        R: 'A',
        S: 'X',
        T: 'G',
        U: 'Y',
        V: 'I',
        W: 'P',
        X: 'S',
        Y: 'U',
        Z: 'Q'
    })
};

// const Rotors = {
//     I: {
//         A: {forwardShift: 4, reverseShift: 20,turnOver: false},
//         B: {forwardShift: 9, reverseShift: 21, turnOver: false},
//         C: {forwardShift: 10, reverseShift: 22, turnOver: false},
//         D: {forwardShift: 2, reverseShift: 3, turnOver: false},
//         E: {forwardShift: 7, reverseShift: 22, turnOver: false},
//         F: {forwardShift: 1, reverseShift: 24,turnOver: false},
//         G: {forwardShift: 23, reverseShift: 25, turnOver: false},
//         H: {forwardShift: 9, reverseShift: 8, turnOver: false},
//         I: {forwardShift: 13, reverseShift: 13, turnOver: false},
//         J: {forwardShift: 16, reverseShift: 16, turnOver: false},
//         K: {forwardShift: 3, reverseShift: 17, turnOver: false},
//         L: {forwardShift: 8, reverseShift: 19, turnOver: false},
//         M: {forwardShift: 2, reverseShift: 16, turnOver: false},
//         N: {forwardShift: 9, reverseShift: 23, turnOver: false},
//         O: {forwardShift: 10, reverseShift: 24, turnOver: false},
//         P: {forwardShift: 18, reverseShift: 4, turnOver: false},
//         Q: {forwardShift: 7, reverseShift: 17, turnOver: true},
//         R: {forwardShift: 3, reverseShift: 6, turnOver: false},
//         S: {forwardShift: 0, reverseShift: 0, turnOver: false},
//         T: {forwardShift: 22, reverseShift: 18, turnOver: false},
//         U: {forwardShift: 6, reverseShift: 23, turnOver: false},
//         V: {forwardShift: 13, reverseShift: 13, turnOver: false},
//         W: {forwardShift: 5, reverseShift: 17, turnOver: false},
//         X: {forwardShift: 20, reverseShift: 19, turnOver: false},
//         Y: {forwardShift: 4, reverseShift: 16, turnOver: false},
//         Z: {forwardShift: 10, reverseShift: 10, turnOver: false}
//     },
//     II: {
//         A: {forwardShift: 0, reverseShift: 0, turnOver: false},
//         B: {forwardShift: 8, reverseShift: 8, turnOver: false},
//         C: {forwardShift: 1, reverseShift: 13, turnOver: false},
//         D: {forwardShift: 7, reverseShift: 25, turnOver: false},
//         E: {forwardShift: 14, reverseShift: 21, turnOver: true},
//         F: {forwardShift: 3, reverseShift: 17, turnOver: false},
//         G: {forwardShift: 11, reverseShift: 11, turnOver: false},
//         H: {forwardShift: 13, reverseShift: 4, turnOver: false},
//         I: {forwardShift: 15, reverseShift: 23, turnOver: false},
//         J: {forwardShift: 18, reverseShift: 18, turnOver: false},
//         K: {forwardShift: 1, reverseShift: 19, turnOver: false},
//         L: {forwardShift: 22, reverseShift: 25, turnOver: false},
//         M: {forwardShift: 10, reverseShift: 2, turnOver: false},
//         N: {forwardShift: 6, reverseShift: 6, turnOver: false},
//         O: {forwardShift: 24, reverseShift: 10, turnOver: false},
//         P: {forwardShift: 13, reverseShift: 5, turnOver: false},
//         Q: {forwardShift: 0, reverseShift: 0, turnOver: false},
//         R: {forwardShift: 15, reverseShift: 15, turnOver: false},
//         S: {forwardShift: 7, reverseShift: 12, turnOver: false},
//         T: {forwardShift: 20, reverseShift: 20, turnOver: false},
//         U: {forwardShift: 21, reverseShift: 13, turnOver: false},
//         V: {forwardShift: 3, reverseShift: 2, turnOver: false},
//         W: {forwardShift: 9, reverseShift: 16, turnOver: false},
//         X: {forwardShift: 24, reverseShift: 11, turnOver: false},
//         Y: {forwardShift: 16, reverseShift: 23, turnOver: false},
//         Z: {forwardShift: 5, reverseShift: 19, turnOver: false}
//     },
//     III: {
//         A: {forwardShift: 1, reverseShift: 19, turnOver: false},
//         B: {forwardShift: 2, reverseShift: 25, turnOver: false},
//         C: {forwardShift: 3, reverseShift: 4, turnOver: false},
//         D: {forwardShift: 4, reverseShift: 24, turnOver: false},
//         E: {forwardShift: 5, reverseShift: 11, turnOver: false},
//         F: {forwardShift: 6, reverseShift: 23, turnOver: false},
//         G: {forwardShift: 22, reverseShift: 12, turnOver: false},
//         H: {forwardShift: 8, reverseShift: 22, turnOver: false},
//         I: {forwardShift: 9, reverseShift: 8, turnOver: false},
//         J: {forwardShift: 10, reverseShift: 21, turnOver: false},
//         K: {forwardShift: 13, reverseShift: 10, turnOver: false},
//         L: {forwardShift: 10, reverseShift: 20, turnOver: false},
//         M: {forwardShift: 13, reverseShift: 9, turnOver: false},
//         N: {forwardShift: 0, reverseShift: 0, turnOver: false},
//         O: {forwardShift: 10, reverseShift: 11, turnOver: false},
//         P: {forwardShift: 15, reverseShift: 18, turnOver: false},
//         Q: {forwardShift: 18, reverseShift: 8, turnOver: false},
//         R: {forwardShift: 5, reverseShift: 17, turnOver: false},
//         S: {forwardShift: 14, reverseShift: 5, turnOver: false},
//         T: {forwardShift: 7, reverseShift: 16, turnOver: false},
//         U: {forwardShift: 16, reverseShift: 2, turnOver: false},
//         V: {forwardShift: 17, reverseShift: 16, turnOver: true},
//         W: {forwardShift: 24, reverseShift: 21, turnOver: false},
//         X: {forwardShift: 21, reverseShift: 13, turnOver: false},
//         Y: {forwardShift: 18, reverseShift: 16, turnOver: false},
//         Z: {forwardShift: 15, reverseShift: 13, turnOver: false}
//     },
//     IV: {
//         A: {forwardShift: 4, turnOver: false},
//         B: {forwardShift: 17, turnOver: false},
//         C: {forwardShift: 12, turnOver: false},
//         D: {forwardShift: 18, turnOver: false},
//         E: {forwardShift: 11, turnOver: false},
//         F: {forwardShift: 20, turnOver: false},
//         G: {forwardShift: 3, turnOver: false},
//         H: {forwardShift: 19, turnOver: false},
//         I: {forwardShift: 16, turnOver: false},
//         J: {forwardShift: 7, turnOver: true},
//         K: {forwardShift: 10, turnOver: false},
//         L: {forwardShift: 23, turnOver: false},
//         M: {forwardShift: 5, turnOver: false},
//         N: {forwardShift: 20, turnOver: false},
//         O: {forwardShift: 9, turnOver: false},
//         P: {forwardShift: 22, turnOver: false},
//         Q: {forwardShift: 23, turnOver: false},
//         R: {forwardShift: 14, turnOver: false},
//         S: {forwardShift: 1, turnOver: false},
//         T: {forwardShift: 13, turnOver: false},
//         U: {forwardShift: 16, turnOver: false},
//         V: {forwardShift: 8, turnOver: false},
//         W: {forwardShift: 6, turnOver: false},
//         X: {forwardShift: 15, turnOver: false},
//         Y: {forwardShift: 24, turnOver: false},
//         Z: {forwardShift: 2, turnOver: false}
//     },
//     V: {
//         A: {forwardShift: 21, turnOver: false},
//         B: {forwardShift: 24, turnOver: false},
//         C: {forwardShift: 25, turnOver: false},
//         D: {forwardShift: 14, turnOver: false},
//         E: {forwardShift: 2, turnOver: false},
//         F: {forwardShift: 3, turnOver: false},
//         G: {forwardShift: 13, turnOver: false},
//         H: {forwardShift: 17, turnOver: false},
//         I: {forwardShift: 12, turnOver: false},
//         J: {forwardShift: 6, turnOver: false},
//         K: {forwardShift: 8, turnOver: false},
//         L: {forwardShift: 18, turnOver: false},
//         M: {forwardShift: 1, turnOver: false},
//         N: {forwardShift: 20, turnOver: false},
//         O: {forwardShift: 23, turnOver: false},
//         P: {forwardShift: 8, turnOver: false},
//         Q: {forwardShift: 10, turnOver: false},
//         R: {forwardShift: 5, turnOver: false},
//         S: {forwardShift: 20, turnOver: false},
//         T: {forwardShift: 16, turnOver: false},
//         U: {forwardShift: 22, turnOver: false},
//         V: {forwardShift: 19, turnOver: false},
//         W: {forwardShift: 9, turnOver: false},
//         X: {forwardShift: 7, turnOver: false},
//         Y: {forwardShift: 4, turnOver: false},
//         Z: {forwardShift: 11, turnOver: true}
//     },
//     VI: {
//         A: {forwardShift: 9, turnOver: false},
//         B: {forwardShift: 14, turnOver: false},
//         C: {forwardShift: 4, turnOver: false},
//         D: {forwardShift: 18, turnOver: false},
//         E: {forwardShift: 10, turnOver: false},
//         F: {forwardShift: 15, turnOver: false},
//         G: {forwardShift: 6, turnOver: false},
//         H: {forwardShift: 24, turnOver: false},
//         I: {forwardShift: 16, turnOver: false},
//         J: {forwardShift: 7, turnOver: false},
//         K: {forwardShift: 17, turnOver: false},
//         L: {forwardShift: 19, turnOver: false},
//         M: {forwardShift: 1, turnOver: true},
//         N: {forwardShift: 20, turnOver: false},
//         O: {forwardShift: 11, turnOver: false},
//         P: {forwardShift: 2, turnOver: false},
//         Q: {forwardShift: 13, turnOver: false},
//         R: {forwardShift: 19, turnOver: false},
//         S: {forwardShift: 8, turnOver: false},
//         T: {forwardShift: 25, turnOver: false},
//         U: {forwardShift: 3, turnOver: false},
//         V: {forwardShift: 16, turnOver: false},
//         W: {forwardShift: 12, turnOver: false},
//         X: {forwardShift: 5, turnOver: false},
//         Y: {forwardShift: 21, turnOver: false},
//         Z: {forwardShift: 23, turnOver: true}
//     },
//     VII: {
//         A: {forwardShift: 13, turnOver: false},
//         B: {forwardShift: 24, turnOver: false},
//         C: {forwardShift: 7, turnOver: false},
//         D: {forwardShift: 4, turnOver: false},
//         E: {forwardShift: 2, turnOver: false},
//         F: {forwardShift: 12, turnOver: false},
//         G: {forwardShift: 22, turnOver: false},
//         H: {forwardShift: 16, turnOver: false},
//         I: {forwardShift: 4, turnOver: false},
//         J: {forwardShift: 15, turnOver: false},
//         K: {forwardShift: 8, turnOver: false},
//         L: {forwardShift: 11, turnOver: false},
//         M: {forwardShift: 15, turnOver: true},
//         N: {forwardShift: 1, turnOver: false},
//         O: {forwardShift: 6, turnOver: false},
//         P: {forwardShift: 16, turnOver: false},
//         Q: {forwardShift: 10, turnOver: false},
//         R: {forwardShift: 17, turnOver: false},
//         S: {forwardShift: 3, turnOver: false},
//         T: {forwardShift: 18, turnOver: false},
//         U: {forwardShift: 21, turnOver: false},
//         V: {forwardShift: 9, turnOver: false},
//         W: {forwardShift: 14, turnOver: false},
//         X: {forwardShift: 19, turnOver: false},
//         Y: {forwardShift: 5, turnOver: false},
//         Z: {forwardShift: 20, turnOver: true}
//     },
//     VIII: {
//         A: {forwardShift: 5, turnOver: false},
//         B: {forwardShift: 9, turnOver: false},
//         C: {forwardShift: 14, turnOver: false},
//         D: {forwardShift: 4, turnOver: false},
//         E: {forwardShift: 15, turnOver: false},
//         F: {forwardShift: 6, turnOver: false},
//         G: {forwardShift: 17, turnOver: false},
//         H: {forwardShift: 7, turnOver: false},
//         I: {forwardShift: 20, turnOver: false},
//         J: {forwardShift: 18, turnOver: false},
//         K: {forwardShift: 25, turnOver: false},
//         L: {forwardShift: 7, turnOver: false},
//         M: {forwardShift: 3, turnOver: true},
//         N: {forwardShift: 16, turnOver: false},
//         O: {forwardShift: 11, turnOver: false},
//         P: {forwardShift: 2, turnOver: false},
//         Q: {forwardShift: 10, turnOver: false},
//         R: {forwardShift: 21, turnOver: false},
//         S: {forwardShift: 12, turnOver: false},
//         T: {forwardShift: 3, turnOver: false},
//         U: {forwardShift: 19, turnOver: false},
//         V: {forwardShift: 13, turnOver: false},
//         W: {forwardShift: 24, turnOver: false},
//         X: {forwardShift: 1, turnOver: false},
//         Y: {forwardShift: 8, turnOver: false},
//         Z: {forwardShift: 22, turnOver: true}
//     }
// };

// const GreekWheels = {
//     Beta: {
//         A: {forwardShift: 11},
//         B: {forwardShift: 3},
//         C: {forwardShift: 22},
//         D: {forwardShift: 6},
//         E: {forwardShift: 17},
//         F: {forwardShift: 23},
//         G: {forwardShift: 7},
//         H: {forwardShift: 1},
//         I: {forwardShift: 15},
//         J: {forwardShift: 13},
//         K: {forwardShift: 5},
//         L: {forwardShift: 16},
//         M: {forwardShift: 4},
//         N: {forwardShift: 25},
//         O: {forwardShift: 15},
//         P: {forwardShift: 2},
//         Q: {forwardShift: 3},
//         R: {forwardShift: 9},
//         S: {forwardShift: 18},
//         T: {forwardShift: 6},
//         U: {forwardShift: 12},
//         V: {forwardShift: 10},
//         W: {forwardShift: 24},
//         X: {forwardShift: 10},
//         Y: {forwardShift: 16},
//         Z: {forwardShift: 19}
//     },
//     Gamma: {
//         A: {forwardShift: 5},
//         B: {forwardShift: 17},
//         C: {forwardShift: 12},
//         D: {forwardShift: 7},
//         E: {forwardShift: 22},
//         F: {forwardShift: 8},
//         G: {forwardShift: 14},
//         H: {forwardShift: 23},
//         I: {forwardShift: 9},
//         J: {forwardShift: 24},
//         K: {forwardShift: 2},
//         L: {forwardShift: 16},
//         M: {forwardShift: 7},
//         N: {forwardShift: 21},
//         O: {forwardShift: 10},
//         P: {forwardShift: 13},
//         Q: {forwardShift: 6},
//         R: {forwardShift: 20},
//         S: {forwardShift: 24},
//         T: {forwardShift: 22},
//         U: {forwardShift: 5},
//         V: {forwardShift: 2},
//         W: {forwardShift: 25},
//         X: {forwardShift: 9},
//         Y: {forwardShift: 11},
//         Z: {forwardShift: 4}
//     }
// };

// const Reflectors = {
//     b: {
//         A: {forwardShift: 4},
//         B: {forwardShift: 12},
//         C: {forwardShift: 8},
//         D: {forwardShift: 13},
//         E: {forwardShift: 22},
//         F: {forwardShift: 15},
//         G: {forwardShift: 18},
//         H: {forwardShift: 15},
//         I: {forwardShift: 1},
//         J: {forwardShift: 25},
//         K: {forwardShift: 18},
//         L: {forwardShift: 3},
//         M: {forwardShift: 3},
//         N: {forwardShift: 14},
//         O: {forwardShift: 23},
//         P: {forwardShift: 23},
//         Q: {forwardShift: 13},
//         R: {forwardShift: 6},
//         S: {forwardShift: 7},
//         T: {forwardShift: 2},
//         U: {forwardShift: 11},
//         V: {forwardShift: 24},
//         W: {forwardShift: 11},
//         X: {forwardShift: 20},
//         Y: {forwardShift: 8},
//         Z: {forwardShift: 19}
//     },
//     c: {
//         A: {forwardShift: 17},
//         B: {forwardShift: 2},
//         C: {forwardShift: 12},
//         D: {forwardShift: 24},
//         E: {forwardShift: 5},
//         F: {forwardShift: 8},
//         G: {forwardShift: 13},
//         H: {forwardShift: 3},
//         I: {forwardShift: 13},
//         J: {forwardShift: 21},
//         K: {forwardShift: 23},
//         L: {forwardShift: 1},
//         M: {forwardShift: 25},
//         N: {forwardShift: 18},
//         O: {forwardShift: 14},
//         P: {forwardShift: 7},
//         Q: {forwardShift: 9},
//         R: {forwardShift: 9},
//         S: {forwardShift: 5},
//         T: {forwardShift: 13},
//         U: {forwardShift: 4},
//         V: {forwardShift: 13},
//         W: {forwardShift: 19},
//         X: {forwardShift: 21},
//         Y: {forwardShift: 22},
//         Z: {forwardShift: 17}
//     }
// };
